[phases.setup]
nixPkgs = ["dotnet-sdk_8"]
aptPkgs = []

[phases.install]
cmds = ["dotnet restore TasteFlow.Api/TasteFlow.Api.csproj"]

[phases.build]
cmds = ["dotnet publish TasteFlow.Api/TasteFlow.Api.csproj -c Release -o ./publish"]

[start]
cmd = "dotnet ./publish/TasteFlow.Api.dll"

[variables]
DOTNET_VERSION = "8.0"
