[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.install]
cmds = ["dotnet restore TasteFlow.Api/TasteFlow.Api.csproj"]

[phases.build]
cmds = ["dotnet publish TasteFlow.Api/TasteFlow.Api.csproj -c Release -o ./publish"]

[start]
cmd = "dotnet TasteFlow.Api/publish/TasteFlow.Api.dll"

